# basic options
title: DevOps 
author: Group 2 
email: Group2@gmail.com
description: DevOps Info
twitter_username: DevOps 
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-titles-from-headings
defaults:
  - scope:
      path: some-path
      layout: some_layout
    values:
      strip_title: true
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: false
